items:
- name: Docs
  tocHref: /
  topicHref: /
  items:
  - name: Visual Studio
    tocHref: /visualstudio/
    topicHref: /visualstudio/
    items:
    - name: Visual Studio Tools pour Docker
      tocHref: /visualstudio/docker
      topicHref: /visualstudio/docker/
ms.openlocfilehash: 958e3173333723e661bc82a5a38daeb2e74e8ff3
ms.sourcegitcommit: be938c7ecd756a11c9de3e6019a490d0e52b4190
ms.translationtype: HT
ms.contentlocale: fr-FR
ms.lasthandoff: 10/31/2018
ms.locfileid: "50673126"
